DinnerDash/TestProject/urls.py
"""TestProject URL Configuration

The `urlpatterns` list routes URLs to view. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import view
    2. Add a URL to urlpatterns:  path('', view.home, name='home')
Class-based view
    1. Add an import:  from other_app.view import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maindisplay.urls')),
    path('', include('admincontrol.urls')),
    path('', include('cart.urls')),
    path('', include('apicall.urls')),

]

handler404 = "maindisplay.views.page_not_found_view"

DinnerDash/cart/urls.py
from django.urls import path
from cart.view import cart_views, ajax_views

urlpatterns = [
    path("cart/", cart_views.DisplayCart.as_view(), name='cart'),
    path("checkout/", cart_views.CheckOut.as_view(), name='checkout'),
    path("previous_orders/", cart_views.PreviousOrder.as_view(), name='previous_order'),

    path("update_item/", ajax_views.UpdateItem.as_view(), name='updateitem'),
    path("session_cart/", ajax_views.SessionCart.as_view(), name='sessionitem'),
    path("checkout-ajax/", ajax_views.CheckoutAjax.as_view(), name='checkoutajax'),
    path("update_status/", ajax_views.OrderstatusAjax.as_view(), name='orderstatusajax'),
    path("change-availability/", ajax_views.ChangeItemAvailability.as_view(), name='itemavailability'),
    path("get_restaurant_category/", ajax_views.GetRestaurantCategory.as_view(), name='getrestaurantcategory'),


]

DinnerDash/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from maindisplay.models import *

orderstatus = (
    ('cart', 'cart'),
    ('ordered', 'ordered'),
    ('paid', 'paid'),
    ('cancelled', 'cancelled'),
    ('completed', 'completed'),
)


class Order(models.Model):
    date_ordered = models.DateTimeField(null=True, blank=True)
    date_Paid = models.DateTimeField(null=True, blank=True)
    date_Completed = models.DateTimeField(null=True, blank=True )

    status = models.CharField("order status",
                              max_length=20,
                              choices=orderstatus,
                              default='cart'
                              )

    customer = models.ForeignKey(User,
                                 on_delete=models.SET_NULL,
                                 help_text='User Detail',
                                 null=True,
                                 blank=True)

    def __str__(self):
        return "{id}: {customer}".format(id=self.id, customer=self.customer)

    @property
    def item_count(self):
        return self.orderitemsaccess.all().count()

    @property
    def item_quantity_count(self):
        orderitems = self.orderitemsaccess.all()
        return sum([orderitem.quantity for orderitem in orderitems])

    @property
    def price_total(self):
        orderitems = self.orderitemsaccess.all()
        return sum([orderitem.orderitemprice for orderitem in orderitems])


class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, related_name='orderitemsaccess')
    quantity = models.PositiveIntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{id}: {order}=> {item}".format(id=self.id, order=self.order, item=self.item)

    @property
    def orderitemprice(self):
        return self.item.price * self.quantity

DinnerDash/templates/checkout.html
{% extends 'common.html' %}
{%load static%}

{% block title %}
    <title>
            Checkout | Foodbear
    </title>
{% endblock %}


{% block style %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/checkout_style.css' %}"/>
{% endblock %}

{% block content %}

    <div class="category-heading my-3 py-3">
        <h3 class="heading"> {{ user|upper}}  Checkout</h3>
    </div>

    {% for order in user.order_set.all %}
        {% if order.status == 'cart' %}
            <div class="item-main-container">
                        <div class="object">
                            <h4 class="total-quantity mx-3 px-3">
                               Total Quantities:  {{ order.item_quantity_count }}
                            </h4>
                            <h4 class="total-price mx-3 px-3">
                               Total Price:  {{ order.price_total }}
                            </h4>
                        </div>
            </div>

            <div class="my-3" style="margin-left: 45%; width: 100%">
                <button
                        id="submitorderbutton"
                        data-orderid="{{ order.id }}"
                        data-action="SUBMITORDER"
                        class="btn btn-info" style="width: 10rem" onclick="submitorder()">
                     Submit order
                </button>
            </div>

        {% endif %}

    {% endfor %}

{% endblock %}
{% block script %}
{% endblock %}

DinnerDash/templates/common.html
{%load static%}
{% load custom_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    {% block title %}
    {% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <link rel="stylesheet" type="text/css" href="{% static 'css/common_style.css' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="https://res.cloudinary.com/dzag0ldw1/image/upload/v1659587773/android-chrome-192x192_wmtz3v.ico">
    {% block style %}
    {% endblock %}
</head>

<body>


<div class="navbar">
 <nav class="navbar navbar-expand-lg navbar-dark bg-light">
        <a class="navbar-brand text-dark" href="{% url 'homepage' %}">Dinner Dash</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'homepage' %}">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>

            {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                      <a class="btn btn-success mr-2" href="{% url 'additem' %}" role="button">Add Item</a>
                      <a class="btn btn-success mr-2" href="{% url 'addcategory' %}" role="button">Add Category</a>
                      <a class="btn btn-success mr-2" href="{% url 'addrestaurant' %}" role="button">Add Restaurant</a>
                      <a class="btn btn-success mr-2" href="{% url 'adminpanel' %}" role="button">Dashboard</a>
                    {% endif %}
                <a class="btn btn-success mr-2" href="{% url 'logout' %}" role="button">Logout</a>

                <a class="nav-link text-dark mr-2" href="{% url 'previous_order' %}" >{{ user.username |upper}}</a>
                <a href="{% url 'cart' %}">
                    <div  class="cart-count pl-3" id="cart-count">
                        {{ user|cart_order_count }}
                    </div>
                    <i class="fa fa-shopping-cart pr-3" style="font-size:25px; aria-hidden="true"> </i>
                </a>

            {% else %}
               <a class="btn btn-success mr-2" href="{% url 'login' %}" role="button">Login</a>
               <a class="btn btn-success mr-2" href="{% url 'signup' %}" role="button">Signup</a>
                <a href="{% url 'cart' %}">
                <div  class="cart-count pl-3" id="cart-count">
                    {% if request.session.cartdata|length != 0 %}
                        {{ request.session.cartdata|length |add:"-1"}}
                    {% else %}
                        {{ request.session.cartdata|length}}
                    {% endif %}
                </div>
                    <i class="fa fa-shopping-cart pr-3" style="font-size:25px; aria-hidden="true">
                    </i>

                </a>
            {% endif %}

        </div>
      </nav>
</div>


<header class="hero">
    {% if heading %}
        <h1>{{ heading }}</h1>
    {% else %}
        <h1>Dinner Dash</h1>
    {% endif %}
</header>

<div class="item-container">
    {% block content %}
    {% endblock %}
</div>



<script type="text/javascript">
    var cf = "{{ csrf_token }}";

    function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }


    var user = "{{ request.user }}";


    const csrftoken = getToken('csrftoken');



</script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

<script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
></script>



<script type="text/javascript" src="{% static 'js/cart2.js' %}"></script>
<script type="text/javascript" src="{% static 'js/checkout.js' %}"></script>
<script type="text/javascript" src="{% static 'js/orderstatus.js' %}"></script>
<script type="text/javascript" src="{% static 'js/itemunavailable.js' %}"></script>


{% block script %}
{% endblock %}

</body>
</html>

DinnerDash/templates/formtemplate.html
{% extends 'common.html' %}
{% load static %}

{% block title %}
    <title>
        {% if formtitle %}
            {{ formtitle }} | Foodbear
        {% else %}
            Form | Foodbear
        {% endif %}
    </title>
{% endblock %}


{% block content %}

<div id="alert" style="position: fixed; Top: 0; right: 0; width: 400px; margin-top: 2rem; margin-right: 1rem; z-index: 1;">
    </div>

  <div class="container h-100 py-3 my-3">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-6 order-2 order-lg-1">

                    {% if form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ form.non_field_errors }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    {% endif %}

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">
                    {% if formtitle %}
                        {{ formtitle }}
                    {% else %}
                         Form
                    {% endif %} </p>

                <form class="mx-1 mx-md-4 " method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                  <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">

                            {% if field.errors %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                    {{ field.errors }}
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                            {% endif %}

                      <label class="form-label">{{ field.label_tag }}</label>
                        {{ field }}

                    </div>
                  </div>

                    {% endfor %}

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">
                            {% if buttonname %}
                                {{ buttonname }}
                            {% else %}
                                Submit
                            {% endif %}
                    </button>
                  </div>

                    <div style="width: 100%;">
                        {% if formtitle == 'Login' %}
                            <p> Don't have account, <a href="{% url 'signup' %}" class="text-primary">Register Now</a></p>
                        {% elif formtitle == 'Signup User' %}
                            <p> Already have account, <a href="{% url 'login' %}" class="text-primary">Login Now</a></p>
                        {% endif %}
                    </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-6 d-flex align-items-center order-1 order-lg-2">

                  <img class="Signup Image" src="https://res.cloudinary.com/dzag0ldw1/image/upload/v1659177383/cld-sample-4.jpg" class="img-fluid" alt="Sample image" style="width: 100%">


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block script %}
    <script>
    function myFunction(value){
        var format = /[ `!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/;
        console.log(format.test(value));

        if (format.test(value) == true){
            document.getElementById("alert").innerHTML = "<div class='alert alert-danger alert-dismissible fade show' role='alert'>  Only accept Alpha and number in title field.(make sure your username dont contain any space) <button type='button' class='close' data-dismiss='alert' aria-label='Close'> <span aria-hidden='true'>&times;</span> </button> </div>"

            setTimeout(function(){
                document.getElementById("alert").innerHTML = ""
            },3000);
        }
    }

    function Changerestaurantcategory(restaurant){
        if (restaurant != '') {
            console.log(restaurant);



            var url = '/get_restaurant_category/'
            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                },

                body: JSON.stringify({'restaurant': restaurant})
            })
                .then((response) => {
                    return response.json()

                })

                 .then((data) => {
                     console.log(data)

                     field = ""


                     for (let index = 0; index < data.length; index++) {
                         console.log(data[index]['id'] );
                         field += "<div><label><input type='checkbox' name='category' value=" + data[index]['id'] + ">" + data[index]['Name'] + "</label></div>";


                         {#document.getElementById("restaurantcategory").innerHTML = "<label for='restaurantcategory_0'><input type='checkbox' name='category' value='2' id='restaurantcategory_0'>Burgers</label>";#}



                         {#<div id="restaurantcategory"><div>#}
                        {#    <label for="restaurantcategory_0"><input type="checkbox" name="category" value="2" id="restaurantcategory_0">#}
                        {# Burgers</label>#}
                        {##}
                        {#</div><div>#}
                        {#    <label for="restaurantcategory_1"><input type="checkbox" name="category" value="3" id="restaurantcategory_1">#}
                        {# Deal</label>#}
                        {##}
                        {#</div><div>#}
                        {#    <label for="restaurantcategory_2"><input type="checkbox" name="category" value="4" id="restaurantcategory_2">#}
                        {# Breakfast</label>#}
                        {##}
                        {#</div><div>#}
                        {#    <label for="restaurantcategory_3"><input type="checkbox" name="category" value="5" id="restaurantcategory_3">#}
                        {# Desifood</label>#}
                        {##}
                        {#</div><div>#}
                        {#    <label for="restaurantcategory_4"><input type="checkbox" name="category" value="6" id="restaurantcategory_4">#}
                        {# allo matar</label>#}
                        {##}
                        {#</div>#}
                        {#</div>#}
                     }

                     console.log(field)
                    document.getElementById("restaurantcategory").innerHTML = field

                })







        }
    }

    </script>
{% endblock %}

DinnerDash/templates/itemdetail.html
{% extends 'common.html' %}
{%load static%}
{% load custom_tags %}


{% block title %}
    <title>
        {% if item.title %}
            {{ item.title }} | Foodbear
        {% else %}
            Item Detail | Foodbear
        {% endif %}
    </title>
{% endblock %}


{% block style %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/itemdetail_style.css' %}"/>
{% endblock %}

{%block content%}

    <div id="alert" style="position: fixed; Top: 0; right: 0; width: 400px; margin-top: 2rem; margin-right: 1rem;">
    </div>

<div class="detail-container  my-3" style="margin-bottom: 10rem!important;">
    <div class="left-side" >
        {% if item.images.all %}
        <div id="nextimage" class="carousel slide imagecarousel" data-ride="carousel">
          <div class="carousel-inner">
              {% for image in item.images.all%}
                    <div class="carousel-item
                        {% if image.id == item.images.all.first.id %}
                              active
                          {% endif %} ">
                      <img class="d-block w-100" src="{{ image.photo.url }}"
                           alt="Item image" style="height: 400px;">
                    </div>
              {% endfor %}
          </div>

          <a class="carousel-control-prev" href="#nextimage" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#nextimage" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        {% endif %}

    </div>

        <div  class="right-side pl-3" style="border: 2px solid brown">
        <div id="item-detail">
            <h3 class="object-heading my-2" style="text-align: center; width: 90%; border: 1px solid red; border-radius: 2rem; margin: auto;">{{ item.title | upper}}</h3>
            <p class="object-description " style="width: 90%; margin-bottom: 2rem">{{ item.description }}</p>
            <div class="object-action">
                <h4 class="object-price mt-2" style="text-align:center; width: 50%"> PKR {{ item.price }}</h4>

                {% if item.available %}
                    {% if user.is_anonymous %}

                        <button data-quantity="1"
                                data-product="{{ item.id }}"
                                data-action="ADD"
                                type="button"

                                onclick="perform_ajax_update_session_cart(
                                                            '{{ item.id }}',
                                                                '1',
                                                                'ADD',
                                                            'detail')"


                                class="object-add-cart btn ml-3" style="width: 50%">ADD TO CART</button>

                    {% else %}

                        <button data-quantity="1"
                                data-product="{{ item.id }}"
                                data-action="ADD"
                                type="button"

                                onclick="perform_ajax_update_cart(
                                                            {{ item.id }},
                                                                'ADD',
                                                            'detail')"


                                class="object-add-cart btn ml-3" style="width: 50%">ADD TO CART</button>

                    {% endif %}


                {% endif %}
            </div>
            <div style="width: 100%">
                 {% if user.is_anonymous %}
                        {% for item_id,item_object in request.session.cartdata.items %}
                            {% if item_id == item.id|stringformat:"i" %}
                                <p> Quantity in Cart: <b>{{ item_object.item_quantity }}</b></p>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                     {% if user|cart_order_item_count %}
                         {% for order in user|cart_order_item_count %}
                                {% for o_item in order.orderitem_set.all %}
                                    {% if item.id == o_item.item.id %}

                                    Item quantity in cart: {{ o_item.quantity }}
                                    {% endif %}
                                {% endfor %}
                         {% endfor %}
                     {% endif  %}
                {% endif %}
            </div>
            <div style="width: 100%; margin-top: 1rem">
                <div style="width: 60%; margin: auto;">
                    <a href="{% url 'restaurant' item.restaurant.id %}"><button type="button" class="object-add-cart btn " style="width: 90%;">Back</button></a>
                </div>
            </div>
            {% if user.is_staff  %}
            <div style="width: 100%; margin-top: 1rem">
                <div style="width: 60%; margin: auto;">
                 <a style="margin-top: 2rem" class="my-3 mr-3" href="{% url 'updateitem' item.id %}"><button type="button" class="object-add-cart btn " style="width: 90%;">Edit Item</button></a>
                </div>
            </div>

            <div style="width: 100%; margin-top: 1rem">
                <div style="width: 60%; margin: auto;">
                    {% if item.available %}
                        <button
                                id="changeavailability"
                                data-orderid="{{ item.id }}"
                                data-action="unavailable"
                                class="object-add-cart btn " onclick="itemavailability()" style="width: 90%;">Mark as Unavailable
                        </button>
                    {% else %}
                        <button
                                id="changeavailability"
                                data-orderid="{{ item.id }}"
                                data-action="available"
                                class="object-add-cart btn ml-3" onclick="itemavailability()" style="width: 90%;">Mark as Available
                        </button>
                    {% endif %}
                </div>
            </div>
            {% endif %}


        </div>
    </div>
</div>
{% endblock %}

{% block script %}
    <script>
    function refresh_item_detail(Response){

    if(Response == 'Reject'){

            document.getElementById("alert").innerHTML = "<div class='alert alert-danger alert-dismissible fade show' role='alert'>  Can't add different Restaurant Item in Cart Once <button type='button' class='close' data-dismiss='alert' aria-label='Close'> <span aria-hidden='true'>&times;</span> </button> </div>"

            setTimeout(function(){
                document.getElementById("alert").innerHTML = ""
            },3000);


        }
        else {
            $( "#item-detail" ).load(window.location.href + " #item-detail" );
            $( "#cart-count" ).load(window.location.href + " #cart-count" );
            document.getElementById("alert").innerHTML = "<div class='alert alert-success alert-dismissible fade show' role='alert'>  Item added to cart. <button type='button' class='close' data-dismiss='alert' aria-label='Close'> <span aria-hidden='true'>&times;</span> </button> </div>"

            setTimeout(function(){
                document.getElementById("alert").innerHTML = ""
            },3000);

        }

    }

    </script>
{% endblock %}